kind: ConfigMap
apiVersion: v1
metadata:
  name: cilium-config
  namespace: kube-system
data:
  # This etcd-config contains the etcd endpoints of your cluster. If you use
  # TLS please make sure you uncomment the ca-file line and add the respective
  # certificate has a k8s secret, see explanation below in the comment labeled
  # "ETCD-CERT"
  etcd-config: |-
    ---
    endpoints:
{%- for endpoints in  salt.caasp_etcd.get_endpoints().split(',') %}
    - {{ endpoints }}
{%- endfor %}
    #
    # In case you want to use TLS in etcd, uncomment the following line
    # and add the certificate as explained in the comment labeled "ETCD-CERT"
    ca-file: '/etc/pki/trust/anchors/SUSE_CaaSP_CA.crt'
    #
    # In case you want client to server authentication, uncomment the following
    # lines and add the certificate and key in cilium-etcd-secrets below
    key-file: '{{ pillar['ssl']['cilium_key'] }}'
    cert-file: '{{ pillar['ssl']['cilium_crt'] }}'

  # If you want to run cilium in debug mode change this value to true
  debug: "false"
  disable-ipv4: "false"
