[template]
src = "haproxy.cfg.tmpl"
dest = "/etc/haproxy/haproxy.cfg"
uid = 0
gid = 0
mode = "0644"
keys = [
    "/registry/services/specs/default/portus",
    "/registry/services/specs/default/registry",
]
check_cmd = "haproxy -f {{.src}} -c"
reload_cmd = "systemctl reload haproxy"
